const PER_PAGE = 50;
const PAGES_PER_GENRE = 1;
const PAGES_PER_TAG = 1;
const GENRES_TO_FETCH_COUNT = 6;
const TAGS_TO_FETCH_COUNT = 8;
const MAX_RECOMMENDATIONS = 30;

const SHRINKAGE_K = 8;
const TAG_SHRINKAGE_K = 2;
const TAG_MULTIPLIER = 4.0;
const TAG_EXPONENT = 2.2;
const NEG_GENRE_PENALTY = 1.0;
const NEGATIVE_TAG_FACTOR = 0.6;

const RELEVANT_TAGS = [
  'achronological order',
  'agender',
  'agriculture',
  'alternate universe',
  'anachronism',
  'anthology',
  'anthropomorphism',
  'anti-hero',
  'aromantic',
  'asexual',
  'athletics',
  'autobiographical',
  'band',
  'battle royale',
  'biographical',
  'bisexual',
  'body horror',
  "boys' love",
  'camping',
  'cars',
  'cgi',
  'chibi',
  'chuunibyou',
  'class struggle',
  'classic literature',
  'college',
  'coming of age',
  'cosmic horror',
  'crime',
  'criminal organization',
  'cultivation',
  'cute boys doing cute things',
  'cute girls doing cute things',
  'cyberpunk',
  'death game',
  'denpa',
  'detective',
  'disability',
  'dissociative identities',
  'drugs',
  'dungeon',
  'dystopian',
  'eco-horror',
  'economics',
  'educational',
  'ensemble cast',
  'environmental',
  'episodic',
  'ero guro',
  'fairy tale',
  'family life',
  'fashion',
  'female harem',
  'found family',
  'full cgi',
  'gangs',
  'gore',
  'guns',
  'henshin',
  'hikikomori',
  'historical',
  'idol',
  'iyashikei',
  'josei',
  'kemonomimi',
  'kids',
  'lgbtq+ themes',
  'lost civilization',
  'love triangle',
  'mafia',
  'magic',
  'male harem',
  'martial arts',
  'medieval',
  'meta',
  'military',
  'mixed gender harem',
  'mixed media',
  'no dialogue',
  'noir',
  'non-fiction',
  'otaku culture',
  'outdoor activities',
  'parenthood',
  'parody',
  'philosophy',
  'politics',
  'post-apocalyptic',
  'primarily adult cast',
  'primarily female cast',
  'primarily male cast',
  'primarily teen cast',
  'psychosexual',
  'real robot',
  'reincarnation',
  'revenge',
  'reverse isekai',
  'rural',
  'satire',
  'school',
  'school club',
  'seinen',
  'shoujo',
  'shounen',
  'slapstick',
  'space opera',
  'steampunk',
  'stop motion',
  'super robot',
  'superhero',
  'surreal comedy',
  'survival',
  'tokusatsu',
  'tragedy',
  'transgender',
  'travel',
  'urban',
  'urban fantasy',
  'villainess',
  'war',
  'work',
  'yakuza',
  'youkai',
  'yuri'
];
